//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientInventoryRL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory : System.ComponentModel.INotifyPropertyChanged
    {
    
    
    #region Implement 
     
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    public void OnPropertyChanged([System.Runtime.CompilerServices.CallerMemberName]string prop = "")
    {
        if (PropertyChanged != null)
            PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(prop));
    }
     
     #endregion
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.InventoryModifiers = new HashSet<InventoryModifiers>();
            this.Slot = new HashSet<Slot>();
        }
    
        private int _Id;
        public int Id 
        { 
            get
            {
                return _Id;
            } 
            set
            {
                if(_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
                 
        private int _UserId;
        public int UserId 
        { 
            get
            {
                return _UserId;
            } 
            set
            {
                if(_UserId != value)
                {
                    _UserId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
                 
        private float _MaxWeight;
        public float MaxWeight 
        { 
            get
            {
                return _MaxWeight;
            } 
            set
            {
                if(_MaxWeight != value)
                {
                    _MaxWeight = value;
                    OnPropertyChanged("MaxWeight");
                }
            }
        }
                 
        private float _CurrentWeight;
        public float CurrentWeight 
        { 
            get
            {
                return _CurrentWeight;
            } 
            set
            {
                if(_CurrentWeight != value)
                {
                    _CurrentWeight = value;
                    OnPropertyChanged("CurrentWeight");
                }
            }
        }
                 
    
        private User _User;
        public virtual User User 
        { 
            get
            {
                return _User;
            } 
            set
            {
                if(_User != value)
                {
                    _User = value;
                    OnPropertyChanged("User");
                }
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<InventoryModifiers> _InventoryModifiers;
        public virtual ICollection<InventoryModifiers> InventoryModifiers 
        { 
            get
            {
                return _InventoryModifiers;
            } 
            set
            {
                if(_InventoryModifiers != value)
                {
                    _InventoryModifiers = value;
                    OnPropertyChanged("InventoryModifiers");
                }
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Slot> _Slot;
        public virtual ICollection<Slot> Slot 
        { 
            get
            {
                return _Slot;
            } 
            set
            {
                if(_Slot != value)
                {
                    _Slot = value;
                    OnPropertyChanged("Slot");
                }
            }
        }
    }
}
