//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientInventoryRL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventorySlotModifiers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventorySlotModifiers()
        {
            this.InventoryModifiers = new HashSet<InventoryModifiers>();
            this.Slot = new HashSet<Slot>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeModifiresId { get; set; }
        public int Slots { get; set; }
        public float MaxCapacity { get; set; }
        public byte[] MainImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryModifiers> InventoryModifiers { get; set; }
        public virtual TypeModifires TypeModifires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slot> Slot { get; set; }
    }
}
