//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientInventoryRL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryRLDataBaseEntities1 : DbContext
    {
        public InventoryRLDataBaseEntities1()
            : base("name=InventoryRLDataBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<InventoryModifiers> InventoryModifiers { get; set; }
        public virtual DbSet<InventorySlotModifiers> InventorySlotModifiers { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Slot> Slot { get; set; }
        public virtual DbSet<TypeModifires> TypeModifires { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
