//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientInventoryRL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot : System.ComponentModel.INotifyPropertyChanged
    {
    
    
    #region Implement 
     
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    public void OnPropertyChanged([System.Runtime.CompilerServices.CallerMemberName]string prop = "")
    {
        if (PropertyChanged != null)
            PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(prop));
    }
     
     #endregion
    
    
        private int _Id;
        public int Id 
        { 
            get
            {
                return _Id;
            } 
            set
            {
                if(_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
                 
        private Nullable<int> _ItemId;
        public Nullable<int> ItemId 
        { 
            get
            {
                return _ItemId;
            } 
            set
            {
                if(_ItemId != value)
                {
                    _ItemId = value;
                    OnPropertyChanged("ItemId");
                }
            }
        }
                 
        private int _InventoryId;
        public int InventoryId 
        { 
            get
            {
                return _InventoryId;
            } 
            set
            {
                if(_InventoryId != value)
                {
                    _InventoryId = value;
                    OnPropertyChanged("InventoryId");
                }
            }
        }
                 
        private int _StorageId;
        public int StorageId 
        { 
            get
            {
                return _StorageId;
            } 
            set
            {
                if(_StorageId != value)
                {
                    _StorageId = value;
                    OnPropertyChanged("StorageId");
                }
            }
        }
                 
        private Nullable<int> _QuantityItem;
        public Nullable<int> QuantityItem 
        { 
            get
            {
                return _QuantityItem;
            } 
            set
            {
                if(_QuantityItem != value)
                {
                    _QuantityItem = value;
                    OnPropertyChanged("QuantityItem");
                }
            }
        }
                 
    
        private Inventory _Inventory;
        public virtual Inventory Inventory 
        { 
            get
            {
                return _Inventory;
            } 
            set
            {
                if(_Inventory != value)
                {
                    _Inventory = value;
                    OnPropertyChanged("Inventory");
                }
            }
        }
        private InventorySlotModifiers _InventorySlotModifiers;
        public virtual InventorySlotModifiers InventorySlotModifiers 
        { 
            get
            {
                return _InventorySlotModifiers;
            } 
            set
            {
                if(_InventorySlotModifiers != value)
                {
                    _InventorySlotModifiers = value;
                    OnPropertyChanged("InventorySlotModifiers");
                }
            }
        }
        private Item _Item;
        public virtual Item Item 
        { 
            get
            {
                return _Item;
            } 
            set
            {
                if(_Item != value)
                {
                    _Item = value;
                    OnPropertyChanged("Item");
                }
            }
        }
    }
}
